name: Publish NuGet Packages

on:
  push:
    tags:
      - '*' 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Heading
        run: dotnet restore ./src/Umbraco.Community.PropertyEditors.Heading/Umbraco.Community.PropertyEditors.Heading.csproj
      
      - name: Restore Heading.Assets
        run: dotnet restore ./src/Umbraco.Community.PropertyEditors.Heading.Assets/Umbraco.Community.PropertyEditors.Heading.Assets.csproj

      - name: Build Heading
        run: dotnet build ./src/Umbraco.Community.PropertyEditors.Heading/Umbraco.Community.PropertyEditors.Heading.csproj --configuration Release --no-restore

      - name: Build Heading.Assets
        run: dotnet build ./src/Umbraco.Community.PropertyEditors.Heading.Assets/Umbraco.Community.PropertyEditors.Heading.Assets.csproj --configuration Release --no-restore

      - name: Pack Heading
        run: dotnet pack ./src/Umbraco.Community.PropertyEditors.Heading/Umbraco.Community.PropertyEditors.Heading.csproj --configuration Release --no-build --output ./nupkg

      - name: Pack Heading.Assets
        run: dotnet pack ./src/Umbraco.Community.PropertyEditors.Heading.Assets/Umbraco.Community.PropertyEditors.Heading.Assets.csproj --configuration Release --no-build --output ./nupkg
      
      - name: Push all .nupkg files to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
